"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle2, Circle, Clock, Play, BookOpen, Loader2, PlaySquare, MonitorPlay, FileCode2, Book, ExternalLink, ChevronDown, ChevronUp, CalendarDays } from "lucide-react";
import { useRouter } from "next/navigation";

export default function RoadmapPage() {
  const router = useRouter();
  const [profile, setProfile] = useState<any>(null);
  const [roadmap, setRoadmap] = useState<any>(null);
  const [currentWeekIndex, setCurrentWeekIndex] = useState(0);
  const [completedTopics, setCompletedTopics] = useState<Record<string, boolean>>({});

  useEffect(() => {
    const savedProfile = localStorage.getItem("skillforge_profile");
    const savedRoadmap = localStorage.getItem("skillforge_roadmap");
    const savedProgress = localStorage.getItem("skillforge_progress");
    const savedTopics = localStorage.getItem("skillforge_topic_progress");
    const savedResources = localStorage.getItem("skillforge_resources");
    
    if (savedProfile) setProfile(JSON.parse(savedProfile));
    if (savedRoadmap) setRoadmap(JSON.parse(savedRoadmap));
    if (savedProgress) setCurrentWeekIndex(parseInt(savedProgress, 10));
    if (savedTopics) setCompletedTopics(JSON.parse(savedTopics));
  }, []);

  const completeWeek = (targetWeekIndex: number) => {
    const newIndex = Math.max(currentWeekIndex, targetWeekIndex + 1);
    setCurrentWeekIndex(newIndex);
    localStorage.setItem("skillforge_progress", newIndex.toString());
  };

  const toggleTopic = (weekIndex: number, topicIndex: number) => {
    const key = `${weekIndex}-${topicIndex}`;
    const newProgress = { ...completedTopics, [key]: !completedTopics[key] };
    setCompletedTopics(newProgress);
    localStorage.setItem("skillforge_topic_progress", JSON.stringify(newProgress));

    // Check if all topics in this week are now completed
    const week = roadmap.weeks[weekIndex];
    const allTopicsCompleted = week.topics.every((_: any, i: number) => {
      return newProgress[`${weekIndex}-${i}`];
    });

    if (allTopicsCompleted) {
      completeWeek(weekIndex);
    }
  };

  const exportToCalendar = () => {
    if (!roadmap || !roadmap.weeks) return;
    
    let icsContent = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//SkillForge//Roadmap//EN\r\nCALSCALE:GREGORIAN\r\n";
    
    let currentDate = new Date();
    
    roadmap.weeks.forEach((week: any, index: number) => {
      const startDate = new Date(currentDate);
      startDate.setDate(startDate.getDate() + (index * 7));
      startDate.setHours(9, 0, 0, 0);
      
      const endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 5); 
      endDate.setHours(17, 0, 0, 0);

      const formatDate = (date: Date) => {
        return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
      };

      const topicsList = week.topics.join('\\n- ');
      const description = `Topics for this week:\\n- ${topicsList}\\n\\nGenerated by SkillForge`;

      icsContent += "BEGIN:VEVENT\r\n";
      icsContent += `SUMMARY:SkillForge: ${week.title}\r\n`;
      icsContent += `DESCRIPTION:${description}\r\n`;
      icsContent += `DTSTART:${formatDate(startDate)}\r\n`;
      icsContent += `DTEND:${formatDate(endDate)}\r\n`;
      icsContent += "END:VEVENT\r\n";
    });
    
    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'skillforge-roadmap.ics');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!profile || !roadmap) {
    return (
      <div className="p-8 max-w-4xl mx-auto text-center mt-20">
        <h2 className="text-2xl font-bold mb-4 text-foreground">No Roadmap Found</h2>
        <p className="text-muted-foreground mb-6 font-medium">You need to analyze your skills first to generate a personalized roadmap.</p>
        <button onClick={() => router.push("/dashboard/skills")} className="bg-primary hover:bg-primary/90 text-primary-foreground px-6 py-2 rounded-lg transition-colors shadow-sm font-semibold">
          Go to Skill Gap
        </button>
      </div>
    );
  }

  const totalWeeks = roadmap.weeks?.length || 1;
  const progressPercent = Math.round((currentWeekIndex / totalWeeks) * 100);

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-8 pb-24">
      <div className="flex justify-between items-end mb-8">
        <div>
          <h1 className="text-3xl font-bold mb-2 text-foreground">Personalized Roadmap</h1>
          <p className="text-muted-foreground font-medium">Your custom learning path to become an <span className="text-foreground font-semibold">{profile.targetRole}</span>.</p>
        </div>
        <div className="flex items-center gap-6 hidden sm:flex">
          <button 
            onClick={exportToCalendar}
            className="flex items-center gap-2 px-4 py-2 bg-muted hover:bg-muted/80 text-foreground border border-border rounded-xl font-semibold transition-colors shadow-sm text-sm"
          >
            <CalendarDays className="w-4 h-4 text-indigo-500" />
            Sync to Calendar
          </button>
          <div className="text-right">
            <p className="text-sm text-muted-foreground mb-1 font-medium">Progress</p>
            <div className="text-3xl font-extrabold text-primary">{progressPercent}%</div>
          </div>
        </div>
      </div>

      <div className="w-full bg-muted rounded-full h-2 mb-8 sm:hidden shadow-inner">
        <div className="bg-primary h-2 rounded-full transition-all duration-500 shadow-sm" style={{ width: `${progressPercent}%` }}></div>
      </div>

      <div className="relative border-l-2 border-border ml-4 space-y-12 pb-12">
        {roadmap.weeks?.map((week: any, index: number) => {
          let status = 'upcoming';
          if (index < currentWeekIndex) status = 'completed';
          if (index === currentWeekIndex) status = 'current';
          
          return (
            <motion.div 
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
              key={index} 
              className={`relative pl-8 ${status === 'upcoming' ? 'opacity-50' : 'opacity-100'}`}
            >
              {/* Timeline dot */}
              <div className={`absolute -left-[18px] top-1 p-1 rounded-full border-4 border-background ${status === 'completed' ? 'bg-primary' : status === 'current' ? 'bg-primary animate-pulse' : 'bg-muted border-border'}`}>
                {status === 'completed' ? (
                  <CheckCircle2 className="w-5 h-5 text-primary-foreground" />
                ) : status === 'current' ? (
                  <Play className="w-5 h-5 text-primary-foreground" />
                ) : (
                  <Circle className="w-5 h-5 text-muted-foreground" />
                )}
              </div>

              <div className={`bg-card border ${status === 'current' ? 'border-primary/50 shadow-md ring-1 ring-primary/20' : 'border-border shadow-sm'} rounded-3xl p-8 transition-all duration-300`}>
                <div className="flex items-center justify-between mb-6">
                  <h2 className={`text-2xl font-bold ${status === 'completed' ? 'line-through text-muted-foreground' : 'text-foreground'}`}>{week.title}</h2>
                  <span className="text-sm text-muted-foreground font-medium flex items-center gap-1.5 px-3 py-1 bg-muted rounded-full">
                    <Clock className="w-4 h-4" /> {week.duration}
                  </span>
                </div>
                
                <ul className="space-y-3 mb-6">
                  {week.topics?.map((topic: string, i: number) => {
                    const topicKey = `${index}-${i}`;
                    const isTopicCompleted = completedTopics[topicKey] || status === 'completed';
                    
                    return (
                      <li key={i} className="flex items-start gap-3 group">
                        <button 
                          onClick={() => toggleTopic(index, i)}
                          disabled={status === 'completed'}
                          className={`mt-0.5 shrink-0 transition-colors ${status === 'completed' ? 'cursor-not-allowed opacity-70' : 'cursor-pointer'}`}
                        >
                          {isTopicCompleted ? (
                            <div className="w-5 h-5 rounded-md bg-primary flex items-center justify-center shadow-sm">
                              <CheckCircle2 className="w-3.5 h-3.5 text-primary-foreground" />
                            </div>
                          ) : (
                            <div className="w-5 h-5 rounded-md border-2 border-muted-foreground group-hover:border-primary transition-colors bg-background" />
                          )}
                        </button>
                        <span className={`font-medium ${isTopicCompleted ? 'text-muted-foreground line-through' : 'text-foreground'}`}>{topic}</span>
                      </li>
                    );
                  })}
                </ul>

                <div className="flex flex-col sm:flex-row gap-3">
                  <button 
                    onClick={() => router.push(`/dashboard/resources?week=${index}`)}
                    className="flex-1 py-3.5 bg-muted hover:bg-muted/80 text-foreground rounded-xl font-bold transition-colors flex items-center justify-center gap-2 text-sm border border-border shadow-sm"
                  >
                    <BookOpen className="w-4 h-4" /> 
                    View Resources
                  </button>
                  
                  {(status === 'current' || status === 'upcoming') && (
                    <button 
                      onClick={() => completeWeek(index)}
                      className="flex-1 py-3.5 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl font-bold transition-all shadow-md hover:-translate-y-0.5 flex items-center justify-center gap-2 text-sm"
                    >
                      <CheckCircle2 className="w-4 h-4" /> Mark Complete
                    </button>
                  )}
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
      
      {currentWeekIndex >= totalWeeks && totalWeeks > 0 && (
        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="p-10 bg-gradient-to-r from-emerald-500/10 to-primary/10 border border-emerald-500/20 rounded-3xl text-center shadow-lg"
        >
          <div className="w-20 h-20 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6 border border-emerald-500/30">
            <CheckCircle2 className="w-10 h-10 text-emerald-500" />
          </div>
          <h2 className="text-3xl font-extrabold mb-3 text-foreground">Congratulations!</h2>
          <p className="text-muted-foreground mb-8 font-medium max-w-lg mx-auto">You have completed your entire learning roadmap. You are ready to take on the role of <span className="text-foreground font-semibold">{profile.targetRole}</span>.</p>
          <button 
            onClick={() => router.push("/dashboard/projects")}
            className="px-8 py-4 bg-foreground text-background font-bold rounded-xl hover:bg-foreground/90 transition-all shadow-md hover:-translate-y-0.5"
          >
            Build Portfolio Projects
          </button>
        </motion.div>
      )}
    </div>
  );
}
